### ISSUE TITLE
Error during execution of examples/l63/demoKAF.m

### ISSUE THREAD

**Issue by DmytroSytnyk** [dg227/NLSA#2] opened 2022-05-20 13:56 UTC
Hello Dimitrios!

There is a typo in the code of nlsa/utils/nlsa_models/nlsaModelFromPars.m that prevents examples/l63/demoKAF.m from running

Here is a git diff of the fix.

```
diff --git a/nlsa/utils/nlsa_models/nlsaModelFromPars.m b/nlsa/utils/nlsa_models/nlsaModelFromPars.m
index e945218..ec10ff5 100755
--- a/nlsa/utils/nlsa_models/nlsaModelFromPars.m
+++ b/nlsa/utils/nlsa_models/nlsaModelFromPars.m
@@ -276,7 +276,7 @@ if ifOse
                                     'nSample', Out.Res( iR ).nSE, ...
                                     'nBatch',  Out.Res( iR ).nB  );
         oseRecPartition( iR ) = nlsaPartition( ...
-                                    'nSample', Out.Res( iR ).nSRec, ...
+                                    'nSample', Out.Res( iR ).nSERec, ...
                                     'nBatch',  Out.Res( iR ).nBRec ); 
     end
 end

```

Cheers,
Dmytro

**Comment by dg227** [comment] 2022-07-17 02:46
Hi Dmytro,

Thanks for letting me know, the issue is now fixed. There was a duplicate nlsaModelFromPars.m in the repo that was causing issues. Sorry that the fix took long.

**Closed** 2022-07-17 02:46 UTC
